### ISSUE TITLE
производство. снабжение. сбрасывает ограничения качества/цены

### ISSUE THREAD

**Issue by ra81** [cobr123/XioScript#1]
Если например в производстве муки на вкладке снабжения  установить stock. При этом уже добавлен поставщик. Нажимаю Fire. Объем закупки увеличивается согласно правилу скрипта, НО при этом скидываются все ограничения по качеству и цены. Ставит НИКОГДА не разрывать контракт, и мин качество для разрыва ставит 0. Такое ТОЛЬКО если скрипт изменяет объем закупки. Если не меняет то не сбрасывает эти ограничения.

По факту ломает очень важную опцию. Пользоваться как бы нельзя если качество выхода на производстве важно. Могут подсунуть лубое качество и все скушает.

По факту сброс происходит при выборе так же опции required. Видимо это системная беда.

**Comment by cobr123** [comment]
в 12.0.65 добавил сохранение настроенных ограничений закупок

**Comment by ra81** [comment]
Не успел моргнуть уже фиксы. Вот это я понимаю девелопмент :)

**Comment by ra81** [comment]
снабжение производства работает. все сохраняет. Еще попроверяю, если ок, закрою.

**Comment by ra81** [comment]
снабжение магазинов нормально. складов тоже. очевидно поправлено централизованно. все выглядит ок.
