### ISSUE TITLE
ограничение на макс 500% по зарплате не работает.

### ISSUE THREAD

**Issue by ra81** [cobr123/XioScript#14]
Скрипт в казахстане где хорошо проверять на тупарях, поставил 700% от городской. Хотя у меня стояло 80-500 ограничение. Что то не работает с верхней планкой.

**Comment by ra81** [comment]
залез в код. полагаю корявка тут http://www.pixic.ru/i/y061z3b43072i260.png
ну она там повторяется

**Comment by cobr123** [comment]
поправил в 12.0.71

**Comment by ra81** [comment]
проверено. работает.
