### ISSUE TITLE
опции розницы и других настроек перепутаны в коде

### ISSUE THREAD

**Issue by ra81** [cobr123/XioScript#18]
Обратил внимание что вроде бы задаю одно а в рознице цену ставит другую. Задел в код изучая процесс. Там обнаружил что как то многие опции перепутаны и выводятся видимо в одном порядке а сохраняются в другом порядке, или я не очень понимаю почему так
http://img-fotki.yandex.ru/get/198569/231592473.1/0_138080_55ad5cdc_orig.jpg

Это не только розницы касается, есть смысл все проверить так как такое много где наблюдается.

**Comment by cobr123** [comment]
Есть порядок сохранения и порядок отображения. Например есть три пункта в настройке и нужно добавить новый после первого пункта. в порядке отображения он будет второй, а в порядке отображения четвертый.

**Comment by ra81** [comment]
видимо так и есть. Еще раз в код залез, отсмотрел логику и кажется что она работает как написано.
