### ISSUE TITLE
ограничение на миним зарплату 80% от средней

### ISSUE THREAD

**Issue by ra81** [cobr123/XioScript#2]
В совсем не редких случаях есть необходимость ставить зарплату НИЖЕ 80% но с полной загрузкой ТОП1. И если руками все настроить заранее, то потом скрипт РЕЗКО ЗАВЫШАЕТ зарплату от чего эффективность топ1 ломается. Нужно добавить вариант типо МаксимумБез80%.
Я на коленке себе в скрипт такое добавил. И отлично работает. Но как то загнать в исходники надо. Когда ты шибко большая шишка возможно такое не надо, но для не очень крупных дядь вполне важная опция. Особенно для офисов.

Я понимаю что это приводит к отупению рабов если их обучать, НО это уже вопрос разумности действий пользователя. Если ты учишь тогда ставь с ограничениями. А если не учишь тогда они НЕ нужны. Бывает нужно нагнать массу тупарей, для объема.

**Comment by cobr123** [comment]
в 12.0.64 добавил новую настройку "min 80%","Without low bound"

**Comment by ra81** [comment]
Думаю более функционально было бы 3 опцию вставить. 2 опцию оставить как есть. А в 3 опции чел может выбрать - Лимиты оба, Лимит сверху тока. Нет лимитов вообще. 
Так можно регулировать на любой опции работу лимитов. Какие выбрал такие и применяются. Очень здорово.

**Comment by cobr123** [comment]
в 12.0.67 сделал варианты: "min 80% max 500%", "max 500%", "min 80%", "No bound"

**Comment by ra81** [comment]
спасибо. хотел сам поправить запушить в дев ветку но пока я писал уже все сделано. Работает.
