### ISSUE TITLE
Опция продажи в 6 процентов рынка (нововведение)

### ISSUE THREAD

**Issue by vulh** [cobr123/XioScript#21]
Смысл интереса вот в чём, учитывая наличия этого скрипта время контроля за магазинами сильно уменьшаетя. Не нужно тратить кучу времени на них.
Соответственно имеет смысл ставит  в городе не 1 магазин, а два магазина меньших размеров и занимать в каждом не более 8 процентов рынка. 
Мы получим больше накладных расходов на рекламу, однако будет два жирных плюса один жирней другого-)
1) Кждая единица товара будет продана дороже, выгода по марже.
2) магазина меньших размеров сожрут меньше рабов! Экономия топ-3, это то, чего ради вся эта песня, имея тужк квалу можно получить больше тележек=)

Реализация в виде новой опции в торговом зале, опция работает точно также как маркет, только порог регулирования от 4.5 до 8 процентов рынка.

**Comment by ra81** [comment]
я тебе в личку в игре ссыль кинул ты туда сходи и туда писать. а сюда пока это писать не надо. по рознице мы там обсуждать давай. с глаз долой :). То что ты пишешь как туда писать надо и это разбирается там.

**Comment by vulh** [comment]
Туда я уже отписал, лично по мне розница вылизана почти идеально в скрипте.  Он делает ровно то и так, как это делал бы я сам. Только в маги он не забывает заходить в отличии от меня.
Мне не хватат только этой опции)

**Comment by ra81** [comment]
это я сделаю сам могу в принципе. Фигня вопрос вообще. А вот баги текущих опций я там изложил.

**Comment by cobr123** [comment]
в 12.0.77 добавил вариант "Market 6%"
