### ISSUE TITLE
Virt design change

### ISSUE THREAD

**Issue by Omahen** [cobr123/XioScript#27]
After the design change, xioscript buttons appear, I can see the settings of my units and run the script. However, it just returns a message (for all my companies):

"Subdivision 3812376 is missing from the company. Options have been erased from the Local Storage."

Script only works for offices, but no other units. Really appreciated if you could fix that

**Comment by cobr123** [comment]
I am using version 12.0.144 and everything seems to work fine on the old interface.

**Comment by cobr123** [comment]
oops) today it repeats like you wrote. i will find out how to fix it.

**Comment by cobr123** [comment]
12.0.145 fix: do not auto remove options if subdivision from local storage. instead added button for user to press

**Comment by Omahen** [comment]
Thanks. However I don't think it is fixed. Now I get a message like this:

New suppliers: | 0
Get calls: | 1
Post calls: | 0
Total server calls: | 1
Time: | 0 | min | 4 | sec
All Done!

Subdivision 7000978 seems missing from the company. Click here to erase options of this subdivision from the Local Storage if it is missing.

Same message for all units (I have thousands).

**Comment by cobr123** [comment]
https://virtonomica.ru/api/olga/main/company/units?id=4207337 returns 54 elements and 1 page/ i think it bug in game api https://virtonomica.ru/olga/forum/forum_new/15/topic/130979/view/m:100247474/#100247474

**Comment by cobr123** [comment]
https://virtonomica.ru/api/olga/main/company/units?id=4207337&pagesize=100&pagenum=1&format=debug returns 54 elements and 1 page. I think it`s bug in game api.

**Comment by cobr123** [comment]
unit_class_id=all fixes problem

**Comment by cobr123** [comment]
try 12.0.147

**Comment by Omahen** [comment]
Thank you very much.Didn't try everything yet, but it looks great now.
