### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by Omahen** [cobr123/XioScript#28]
Only required values are shown. Target, Maximum, Overflow shows NaN. Not sure if it affects calculations in any way, but it set salaries in my stores to 0 yesterday. Now it seems right

**Comment by cobr123** [comment]
qualifications page design changed
https://virtonomics.com/olga/main/user/privat/persondata/knowledge

**Comment by cobr123** [comment]
try 12.0.149

**Comment by Omahen** [comment]
Works great, thanks
