### ISSUE TITLE
снабжение не работает если по товару больше 1 поставщика

### ISSUE THREAD

**Issue by ra81** [cobr123/XioScript#3]
Если на вкладке снабжения производства, магазина, услуги есть на товар больше чем 1 поставщик, тогда при нажатии на кнопку Fire все поставки скидываются в 0. И выводится следующее сообщение:

"Subdivision ХХХХХ is missing a supplier, or has too many suppliers!"

Обычно я выбирал Amplifi - One - Local Q но как я понимаю это особо значения не имеет. У предприятия там Stock выбирал. Все равно. Явно из за нескольких поставщиков.

Склад не ломается на этом, и у склада в этом смысле работает. Даже если поставщиков несколько то ошибок такого рода не вылетает. Но там есть свои нюансы, о них другой тикет.

**Comment by cobr123** [comment]
это такая идеология: заказывать на склад, а с него уже на производства\магазины\сервисы\рестораны, чтобы настройка и проверка человеком была на складе, а все остальное даже не смотреть после запуска.

**Comment by ra81** [comment]
ок. предполагал что так и есть. вопросов нет.
