### ISSUE TITLE
снабжение складов. Закупает слишком низкое качество.

### ISSUE THREAD

**Issue by ra81** [cobr123/XioScript#4]
Сразу скажу, если необходимо то алгоритм я могу проработать и дать готовый. Его только вставить в скрипт. 

Когда делаю заказы на склад, то логика скрипт опирается на минимальное цену/качество. В итоге если на рынке выбросили мусор низкого качества и цена/кач у него очень мал, то закупщик его втаривает. Это нам не надо. Всякий хлам закупать - плохо. Снижает общее качество товара и потом не продать.

Ввести опцию, которая бы не давала закупать слишком низкое качество. Реализовать разные варианты. 
НЕ ниже чем на складе*0,95
НЕ ниже чем среднее по риэлму.

Еще более сложный вариант: когда у нас несколько поставщиков уже стоят, у них стоят ограничения на цена и качество. Тогда заказывать новых поставщиков НЕ хуже чем Микс их текущих поставщиков и их ограничений. Пример:
У меня 2 поставщика. Один дает хлам, и дешево. А другой качество и дорого. Миксую до нужной кондиции получаю следующее:
1) объем 200,  Цена 2000, Кач 80. Ограничения: цена не больше 2200. Кач не меньше 76
2) объем 500, Цена 800, Кач 15. Ограничения: цена не больше 880, кач не меньше 13.
Мой текущий микс будет Цена 1142, кач 33,5. Это по фактическим ценам. А если взять и посчитать по ограничениям то микс будет Цена 1257 и кач 31. То есть я не хочу иметь товар хуже качества и дороже по цене. То есть ограничение по цене качеству, при этом качество не хуже чем 31.

Вот такой вот сложный второй алгоритм. Но тут надо додумать детали, если такое возможно, то я проработую весь алгоритм в деталях дам готовый.
Еще хотелось бы чтобы скрипт умел сам делать миксы, но это другой тикет.

**Comment by cobr123** [comment]
нужен готовый

**Comment by ra81** [comment]
уже вопрос отпал
