### ISSUE TITLE
TopManagerStats не показываются в юнитах

### ISSUE THREAD

**Issue by ra81** [cobr123/XioScript#6]
В принципе не актуальная тема так как есть другие скрипты аналогично толка которые показывают на главной странице юнита загрузки по Топ1 и Топ3 и все что с этим связано.

Но все же в скрипте как бы сей функционал заявлен но его нет. Либо дернуть из скрипта kvala_personal_indicator_zarplaty_by_Agor71 и внедрить, либо убрать отсюда вообще. У Агора хорошая стата выводится. Есть смысл внедрить сюда.

**Comment by vulh** [comment]
Не стоит наверное делать совсем уж дикий комбайн, мухи отдельно, котлеты отдельно. 
Инфа по топам в  одном месте, автоматизация в другом.

**Comment by cobr123** [comment]
TopManagerStats заточен под англоязычный интерфейс и меня это устраивает, т.к. для статов у нас уже есть скрипты, к тому же поддерживаеммые авторами.

**Comment by ra81** [comment]
ок. я не имею возражений. все как бы работает неплохо :)
