### ISSUE TITLE
Обрыв контрактов с политикой "Для определенных компаний"

### ISSUE THREAD

**Issue by vulh** [cobr123/XioScript#7]
Собственно есть склад, вот с такими настройками
http://screenshotlink.ru/3db9e13eee8a9174259a1d12463c199d.png
Рыбий Жир в итоге не отгружаются, покупатели волком воют, всё плохо...

При такой настройке должна регулироваться только цена, а политики сбыта  трогаться не должны.

**Comment by cobr123** [comment]
поправил в 12.0.68

**Comment by vulh** [comment]
Спасибо, работает теперь как надо
